version: '3'
services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: ["npm", "start"]

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
